stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:latest

#before script for docker login in each CI job
before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

#build stage for docker build, then push to GitLab Container Registry
build:
  stage: build
  image: docker:19.03.12
  services:
  - docker:19.03.12-dind
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - docker run --rm -v /project:/mkdocs/project $CONTAINER_TEST_IMAGE produce /mkdocs/project/site > result.tar.gz
  artifacts:
    paths:
      - result.tar.gz

#test stage for cat index.html
test:
  stage: test
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - docker run $CONTAINER_TEST_IMAGE gitlab
